apiVersion: cert-manager.io/v1
kind: Certificate
metadata: 
  name: letsencrypt-cert
spec:
  dnsNames:
    - yourdomain.com
  secretName: letsencrypt-cert-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer